name: Docker Build and Push

on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Required to access your code

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}  # From repository variables
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # From repository secrets

      - name: Set up QEMU  # Only needed for multi-arch builds (ARM/AMD)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .  # Build from current directory
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/flask-app:latest  # Match your repo name